NewShop/ViewModels/HomeViewModel.cs
using NewShop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NewShop.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Product> FavProduct { get; set; }
    }
}

NewShop/ViewModels/ProductsListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using NewShop.Data.Models;

namespace NewShop.ViewModels
{
    public class ProductsListViewModel
    {
        public IEnumerable  <Product> AllProducts { get;  set; }
        public string curCategory { get; set;}
    }
}

NewShop/ViewModels/ShopCartViewModel.cs
using NewShop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NewShop.ViewModels
{
    public class ShopCartViewModel
    {
        public ShopCart shopCart { get; set; }
    }
}

NewShop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using NewShop.Data.Interfaces;
using NewShop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NewShop.Controllers
{
    public class HomeController : Controller
    {
        private IAllProducts _ProdRep;

        public HomeController(IAllProducts prodRep)
        {
            _ProdRep = prodRep;
        }

        public ViewResult Index()
        {
            var homeProduct = new HomeViewModel
            {
                FavProduct = _ProdRep.GetFavProducts
            };
            return View(homeProduct);
        }
    }
}

NewShop/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using NewShop.Data;
using NewShop.Data.Interfaces;
using NewShop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NewShop.Controllers
{
    public class OrderController: Controller
    {
        private readonly IAllOrders allOrders;
        private readonly ShopCart shopCart;

        public OrderController(IAllOrders allOrders, ShopCart shopCart)
        {
            this.allOrders  = allOrders;
            this.shopCart = shopCart;
        }
        public IActionResult Checkout()
        {
            return View();
        }
    }
}

NewShop/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using NewShop.Data.Interfaces;
using NewShop.Data.Models;
using NewShop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NewShop.Controllers
{
    public class ProductsController: Controller
    {
        private readonly IAllProducts _AllProducts;
        private readonly IProductsCategory _IProductsCategory;

        public ProductsController(IAllProducts iAllProducts, IProductsCategory iProductsCategory)
        {
            _AllProducts = iAllProducts;
            _IProductsCategory = iProductsCategory;
        }

        [Route("Products/List")]
        [Route("Products/List/{category}")]

        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Product> products = null ;
            string curCategory = "";
            if (string.IsNullOrEmpty(category))
            {
                products = _AllProducts.Products.OrderBy(i => i.Id);
            }
            else
            {
                if(string.Equals("Tort", category, StringComparison.OrdinalIgnoreCase))
                {
                    products = _AllProducts.Products.Where(i => i.Category.CategoryName.Equals("Торт")).OrderBy(i=>i.Id);
                    curCategory = "Торт";
                }
                else if(string.Equals("Pirog", category, StringComparison.OrdinalIgnoreCase)){
                    products = _AllProducts.Products.Where(i => i.Category.CategoryName.Equals("Пирог")).OrderBy(i => i.Id);
                    curCategory = "Пирог";
                }
            }

            var prodObj = new ProductsListViewModel
            {
                AllProducts = products,
                curCategory = curCategory
            };

            ViewBag.Tittle = "Cтраница с пирогами";

            return View(prodObj);
        }

    }
}

NewShop/Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Mvc;
using NewShop.Data.Interfaces;
using NewShop.Data.Models;
using NewShop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NewShop.Controllers
{
    public class ShopCartController : Controller
    {
        private IAllProducts _ProdRep;
        private readonly ShopCart _ShopCart;

        public ShopCartController(IAllProducts prodRep, ShopCart shopCart)
        {
            _ProdRep = prodRep;
            _ShopCart = shopCart;
        }

        public ViewResult Index()
        {
            var items = _ShopCart.getShopItems();
            _ShopCart.listShopItems = items;

            var obj = new ShopCartViewModel
            {
                shopCart = _ShopCart
            };
            return View(obj);
        }
        public RedirectToActionResult addToCart(int id)
        {
            var item = _ProdRep.Products.FirstOrDefault(i => i.Id ==id );
            if(item != null)
            {
                _ShopCart.AddToCart(item);
            }
            return RedirectToAction("Index");
        }
    }
}

NewShop/Views/Home/Index.cshtml
@model HomeViewModel

<h1>Популярное</h1>
<div class="row mt-5 mb-3">
    @{
        foreach (Product product in Model.FavProduct)
        {
            @Html.Partial("AllProducts", product)
        }
    }
</div>

NewShop/Views/Order/Checkout.cshtml
@model Order 
<div class="row">
    <h3>Оформление заказа</h3>
    <form asp-action="Checkout" , method="post" , class="form-horizontal">
        <div class="form-group">
            <label asp-for="Name"></label>
            <div class="col-md-5">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Surname"></label>
            <div class="col-md-5">
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Adress"></label>
            <div class="col-md-5">
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Phone"></label>
            <div class="col-md-5">
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Email"></label>
            <div class="col-md-5">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <input class="btn btn-success" type="submit" value="Оформит заказ"/>

    </form>
</div>  

NewShop/Views/Products/List.cshtml
<h1>Вся продукция</h1>
<h3>@Model.curCategory</h3>
<div class="row mt-5 mb-3">
    @{
        foreach (Product product in Model.AllProducts)
        {
            @Html.Partial("AllProducts", product)
        }
    }
</div>

NewShop/Views/Shared/AllProducts.cshtml
@model NewShop.Data.Models.Product

<div class="col-lg-4">
<img class="img-thumbnail" src="@Model.Image" alt="@Model.Name">
<h2>@Model.Name</h2>
<p>@Model.ShortDescription</p>
<p>Цена: @Model.Prise.ToString()<p>
<p><a class="btn btn-warning " asp-controller="ShopCart" asp-action="addToCart" asp-route-id="@Model.Id">Добавить в корзину</a></p>
</div>

NewShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="~/css/Style.css" type="text/css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">PiroJOK</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto mb-2 mb-md-0">
                        <li class="nav-item active">
                            <a class="nav-link" href="/">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Products/List">Вся продукция</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Products/List/Tort">Тортики</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Products/List/Pirog">Пирожки</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/ShopCart/">Корзина</a>
                        </li>
                        <li class="nav-item">
                            <form class="d-inline-flex">
                                <input class="form-control mr-2" type="search" placeholder="Поиск по сайту" aria-label="Search">
                                <button class="btn btn-outline-success" type="submit">Найти</button>
                            </form>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <a class="nav-link" href="/ShopCart/">Корзина</a>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container mt-5">
        @RenderBody()
    </div>
    <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>© 2020 Malchez, Inc. · <a href="#">Все права защещены</a> · <a href="#">Соглашение</a></p>
    </footer>
    <script src="~/js/bootstrap.min.js"></script>
</body>

</html>

NewShop/Views/ShopCart/Index.cshtml
@model ShopCartViewModel
<div class="container">
    @foreach(var el in Model.shopCart.listShopItems)
    {
    <div class="alert alert-warning mt-3">
        <b>Товар:</b>@el.product.Name<br />
        <b>Стоимость:</b>@el.product.Prise<br />
    </div>
    }
    <hr/>
    <a class="btn btn-danger" asp-controller="Order" asp-action="Checkout">В корзину</a>

</div> 